export type Article = { slug: string; category: string; title: string; dek: string; date: string; body: string[] };

export const articles: Article[] = [
  { slug: 'the-game-is-bigger-than-the-score', category: 'Culture', title: 'The game is bigger than the score.', dek: 'Sport is competition, but it is also memory, identity, ritual and community.', date: '2026-09-03', body: ['A score tells us what happened. It does not tell us why the match mattered.', 'The strongest sporting cultures are built in the spaces around competition: the walk to the ground, the shirt passed between generations, the local pitch, the debate that continues long after the final whistle.', 'UltraWear FC starts with football because football gives us a shared language. The ambition is bigger: build a sports and lifestyle platform that keeps the people around the game at the centre.'] },
  { slug: 'built-by-fans-made-for-everyone', category: 'People', title: 'Built by fans. Made for everyone.', dek: 'A sports platform should help more people find their way into the world of sport.', date: '2026-09-03', body: ['Sport belongs to specialists and newcomers at the same time.', 'That means discovery matters. A useful catalogue should let someone move from a sport to a country, competition, club, team, player and match without losing the thread.', 'That connected architecture is the foundation for UltraWear FC: less friction, more context, and a bigger doorway into sport.'] },
  { slug: 'why-global-sport-needs-better-discovery', category: 'Platform', title: 'Why global sport needs better discovery.', dek: 'The world of sport is enormous. Its digital front doors should reflect that.', date: '2026-09-03', body: ['Millions of teams and competitions exist outside the small set of leagues that dominate global attention.', 'A global catalogue can make that long tail discoverable while still giving major competitions the depth they deserve.', 'The goal is not to flatten sport into one database. It is to connect its layers so every page has a useful next step.'] },
  { slug: 'matchday-without-the-noise', category: 'Matchday', title: 'Matchday without the noise.', dek: 'Scores, fixtures and standings should be fast to understand and easy to trust.', date: '2026-09-03', body: ['Matchday information is most useful when hierarchy is clear: who is playing, when, where the competition sits and what the result means.', 'UltraWear keeps the live surface deliberately focused. The feed supplies the facts; the product supplies the context.', 'As the platform grows, the same principles will apply across more sports and competitions.'] },
  { slug: 'from-football-to-the-world-of-sport', category: 'Vision', title: 'From football to the world of sport.', dek: 'Football is the opening chapter, not the boundary of the brand.', date: '2026-09-03', body: ['UltraWear FC means For Community. That name is a commitment to build around participation, culture and belonging.', 'Football is where the launch begins, but the underlying model is designed for basketball, tennis, running and the sports still to come.', 'The long-term product is a sports world: connected, useful and recognisably human.'] },
  { slug: 'the-people-between-the-lines', category: 'People', title: 'The people between the lines.', dek: 'Teams are more than names in a fixture list.', date: '2026-09-03', body: ['Players, coaches, staff and supporters give every competition its texture.', 'Connecting people to teams, seasons and matches creates context that a scoreboard alone cannot provide.', 'That is why person and membership data are first-class parts of the UltraWear catalogue, not an afterthought.'] },
  { slug: 'a-better-home-for-every-competition', category: 'Platform', title: 'A better home for every competition.', dek: 'A competition page should be the beginning of discovery, not the end.', date: '2026-09-03', body: ['The best competition hubs answer immediate questions and invite the next one.', 'Fixtures lead to matches. Matches lead to teams. Teams lead to people. Standings lead back to the competition story.', 'This connected approach is the product philosophy behind the global catalogue.'] },
  { slug: 'sport-is-a-community-language', category: 'Community', title: 'Sport is a community language.', dek: 'Different sports, places and generations can still share the same sense of belonging.', date: '2026-09-03', body: ['Community is not an extra layer added after the product is built. It is the reason the product exists.', 'UltraWear FC uses sport as a common language and builds the catalogue around the people who make it meaningful.', 'The next chapters will add more sports without losing that centre.'] },
];

export function getArticle(slug: string) { return articles.find((article) => article.slug === slug) ?? null; }
